"use strict";
console.log("---------- Интерфейсы в TypeScript ---------");
console.log("---------- User ---------");
var user = { name: "john" };
console.log(user.name, " - ", user.age);
user.age = 30;
console.log(user.name, " - ", user.age);
console.log("---------- Employee ---------");
var employee = { name: "john", surn: "smit" };
console.log(employee.name, " - ", employee.surn, " - ", employee.age, " - ", employee.salary);
employee.age = 30;
console.log(employee.name, " - ", employee.surn, " - ", employee.age, " - ", employee.salary);
employee.salary = 400;
console.log(employee.name, " - ", employee.surn, " - ", employee.age, " - ", employee.salary);
